apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restart-pod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Theodora2010/testing-k8s.git'
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

