apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restart-pod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://your-repo-url'
    path: 'path-to-your-deployment-directory'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

